iを新しいAPIクライアントで呼び出す
yamader/minskey pull request #51
Opened 2024-03-04 20:12 UTC by Hayao0819

- Userの定義
- APIClientの作成時にtokenを設定
- `getMe`を定義

命名規則適当だけど、`fetchMe`のほうが良かったかもしれない。

2024-03-04 20:16 UTC, Hayao0819 commented
`profileAtom`で

```ts
  const account = get(accountAtom)
  const clients = get(clientsAtom)
  if (!account) return null
  return clients[account.host]?.getMe() ?? null
```

というのが冗長なので、`currentClientAtom`的なものを作ってまとめたほうがいいかもしれない

```ts
const currentClientAtom = atom(get => {
  const account = get(accountAtom)
  if (!account) return null
  return get(clientsAtom)[account.host] ?? null
})
```

2024-03-04 23:58 UTC, yamader commented
profileAtomはうんちなのでとりあえずそこは良いかも

2024-03-05 00:07 UTC, yamader commented
> profileAtomをもとに戻したほうがいい？

別にどっちでも

2024-03-05 00:07 UTC, yamader commented
うんちってのはそもそもprofileAtom自体いらんかもなーの意

2024-03-05 00:09 UTC, yamader commented
あと、これは今後のコミットについてなんだけど別featureからimportするときは`~/features/hoge/fuga`のようにしてほしい

2024-03-05 00:10 UTC, Hayao0819 commented
> あと、これは今後のコミットについてなんだけど別featureからimportするときは`~/features/hoge/fuga`のようにしてほしい

承った
VSCodeの自動補完でやってたんだけど、ちょいイマイチだなと最近思い始めた

2024-03-05 00:13 UTC, yamader commented
自分で何回か~のやつimportしてたら賢くなるかも、知らんけど

2024-03-05 00:20 UTC, Hayao0819 commented
このPRは一旦API面だけにした

2024-03-05 00:40 UTC, yamader requested changes
直してちょ

2024-03-05 00:40 UTC, yamader commented on src/features/api/index.ts
> +    const task = detect(_host, account?.token)
あーこれ考えてなかった
accountsにないホストも渡される可能性があるのでこれはまずい

2024-03-05 00:48 UTC, Hayao0819 commented on src/features/api/index.ts
> +    const task = detect(_host, account?.token)
気づかなかった。直します。

2024-03-05 00:58 UTC, Hayao0819 commented on src/features/api/index.ts
> +    const task = detect(_host, account?.token)
6b68f6e83bbd9ffe8bcfa0f8e786399f6e06933a これでどう？

2024-03-05 01:10 UTC, yamader commented on src/features/api/index.ts
> +    const task = detect(_host, account?.token)
おーん
clientsAtomあたりが本質的にぶっ壊れてる説あるな
とりまこれで良しとするか

2024-03-05 01:11 UTC, merged