Gray out unavailable buttons
yamader/minskey pull request #65
Opened 2024-03-10 07:42 UTC by Hayao0819

2024-03-10 12:43 UTC, yamader requested changes

2024-03-10 12:43 UTC, yamader commented on src/app/(main)/UserMenu.tsx
そこじゃない感

2024-03-11 01:56 UTC, Hayao0819 commented on src/app/(main)/LeftNav.tsx
> +          <NavLink href="/settings/" available={account ? true : false}>
この辺の三項演算子をもっときれいに書けないだろうか

2024-03-12 03:08 UTC, yamader commented on src/app/(main)/LeftNav.tsx
> +          <NavLink href="/settings/" available={account ? true : false}>
`!!account`

2024-03-14 13:00 UTC, yamader commented
たぶんヨシ!

2024-03-14 13:00 UTC, merged